<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="UnitTest_tests.MLTest-20211202043705" tests="2" file="UnitTest_tests.py" time="75.626" timestamp="2021-12-02T04:39:10" failures="1" errors="0" skipped="0">
	<testcase classname="UnitTest_tests.MLTest" name="test_gender" time="34.988" timestamp="2021-12-02T04:39:10"/>
	<testcase classname="UnitTest_tests.MLTest" name="test_age (i=2)" time="40.638" timestamp="2021-12-02T04:38:35">
		<failure type="AssertionError" message="'61 - 70' != '21 - 30'
- 61 - 70
? ^    ^
+ 21 - 30
? ^    ^
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Nova\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\Nova\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 582, in subTest
    yield
  File "e:\niit\semester 7\capstone project ii\project\venv\agender\ui\agender_ui\pybuilder\src\unittest\python\UnitTest_tests.py", line 65, in test_age
    self.assertEqual(prediction, self.age[i])
  File "C:\Users\Nova\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Nova\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Nova\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: '61 - 70' != '21 - 30'
- 61 - 70
? ^    ^
+ 21 - 30
? ^    ^

]]></failure>
	</testcase>
</testsuite>
